version: '3.8'

x-common-variables: &common-variables
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: postgres

services:
  postgres:
    build: ./database
    image: my-postgres-db-acceleratorapp
    restart: always
    ports:
      - "5432:5432"
    environment:
      <<: *common-variables
    volumes:
    - db_data:/var/lib/postgresql/data
  backend:
    build:
      dockerfile: backend.dockerfile
      context: "./api"
    restart: always
    depends_on:
      - postgres
    volumes:
      - /app/node_modules
      - ./api:/app
    ports:
      - "3333:3333"
    environment:
      <<: *common-variables
      DATABASE_URL: database
volumes:
  db_data: